Prevent running on cluster head node

diff --git a/conda-shell b/conda-shell
--- a/conda-shell
+++ b/conda-shell
@@ -1,3 +1,8 @@
 #!/bin/sh
 
+if [ -e /usr/local/sbin/node-type ] && [ $(/usr/local/sbin/node-type) != compute ]; then
+    printf "Error: $0 should only be run on compute nodes.\n"
+    exit 1
+fi
+
 exec /compat/linux/bin/bash
diff --git a/miniconda-installer b/miniconda-installer
--- a/miniconda-installer
+++ b/miniconda-installer
@@ -24,6 +24,11 @@ if [ $# != 0 ]; then
     usage
 fi
 
+if [ -e /usr/local/sbin/node-type ] && [ $(/usr/local/sbin/node-type) != compute ]; then
+    printf "Error: $0 should only be run on compute nodes.\n"
+    exit 1
+fi
+
 for dir in proc dev sys; do
     if [ ! -e /compat/linux/$dir ]; then
 	cat << EOM
